# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(820, 688)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(820, 688))
        MainWindow.setMaximumSize(QtCore.QSize(820, 688))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enableHistoryButton = QtWidgets.QRadioButton(self.groupBox)
        self.enableHistoryButton.setObjectName("enableHistoryButton")
        self.horizontalLayout.addWidget(self.enableHistoryButton, 0, QtCore.Qt.AlignLeft)
        self.loadPatternLabel = QtWidgets.QLabel(self.groupBox)
        self.loadPatternLabel.setObjectName("loadPatternLabel")
        self.horizontalLayout.addWidget(self.loadPatternLabel, 0, QtCore.Qt.AlignRight)
        self.selectPatternBox = QtWidgets.QComboBox(self.groupBox)
        self.selectPatternBox.setObjectName("selectPatternBox")
        self.horizontalLayout.addWidget(self.selectPatternBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.gameWindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameWindow.sizePolicy().hasHeightForWidth())
        self.gameWindow.setSizePolicy(sizePolicy)
        self.gameWindow.setObjectName("gameWindow")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gameWindow)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout.addWidget(self.gameWindow)
        self.controlsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.controlsBox.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.controlsBox.setFont(font)
        self.controlsBox.setObjectName("controlsBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlsBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.playPauseButton = QtWidgets.QPushButton(self.controlsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playPauseButton.sizePolicy().hasHeightForWidth())
        self.playPauseButton.setSizePolicy(sizePolicy)
        self.playPauseButton.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.playPauseButton.setFont(font)
        self.playPauseButton.setObjectName("playPauseButton")
        self.gridLayout_4.addWidget(self.playPauseButton, 0, 0, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.controlsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 0))
        self.clearButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_4.addWidget(self.clearButton, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scaleSlider = QtWidgets.QSlider(self.controlsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleSlider.sizePolicy().hasHeightForWidth())
        self.scaleSlider.setSizePolicy(sizePolicy)
        self.scaleSlider.setMinimum(1)
        self.scaleSlider.setMaximum(100)
        self.scaleSlider.setSliderPosition(51)
        self.scaleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scaleSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.scaleSlider.setObjectName("scaleSlider")
        self.gridLayout_6.addWidget(self.scaleSlider, 1, 0, 1, 1)
        self.scaleLabel = QtWidgets.QLabel(self.controlsBox)
        self.scaleLabel.setObjectName("scaleLabel")
        self.gridLayout_6.addWidget(self.scaleLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 4, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.framerateSlider = QtWidgets.QSlider(self.controlsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framerateSlider.sizePolicy().hasHeightForWidth())
        self.framerateSlider.setSizePolicy(sizePolicy)
        self.framerateSlider.setMinimum(1)
        self.framerateSlider.setMaximum(100)
        self.framerateSlider.setSliderPosition(51)
        self.framerateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.framerateSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.framerateSlider.setObjectName("framerateSlider")
        self.gridLayout_3.addWidget(self.framerateSlider, 1, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.framerateLabel = QtWidgets.QLabel(self.controlsBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.framerateLabel.setFont(font)
        self.framerateLabel.setObjectName("framerateLabel")
        self.gridLayout_3.addWidget(self.framerateLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.controlsBox)
        self.gridLayout.addLayout(self.verticalLayout, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conway\'s Game of Life"))
        self.groupBox.setTitle(_translate("MainWindow", "Configurations"))
        self.enableHistoryButton.setText(_translate("MainWindow", "History"))
        self.loadPatternLabel.setText(_translate("MainWindow", "Load Pattern:"))
        self.infoLabel.setText(_translate("MainWindow", "Draw alive cells or Load a pattern and start the simulation"))
        self.controlsBox.setTitle(_translate("MainWindow", "Controls"))
        self.playPauseButton.setText(_translate("MainWindow", "Play"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.scaleLabel.setText(_translate("MainWindow", "Scale"))
        self.framerateLabel.setText(_translate("MainWindow", "Framerate"))
